server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: log4j2-war

logging:
    config: classpath:log4j2.xml

#http编码配置
http:
  encoding:
    charset: UTF-8
    force: true
    enabled: true