server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: logback

logging:
  config: classpath:config/logback-spring.xml

#http编码配置
http:
  encoding:
    charset: UTF-8
    force: true
    enabled: true