server:
  port: 8080

spring:
  application:
    name: zuul-dynamic-route

eureka:
  client:
    serviceUrl:
      #      可以多个，用逗号分割，逗号跟实际内容之间不能有空格
      defaultZone: http://admin:admin@localhost:5000/eureka/
#配置对外的服务器列表
zuul:
  routes:
    # 示例prefix和 strip-prefix配合使用，去掉前缀
    service:
      url: http://
      path: /**
      strip-prefix: false