TRUNCATE table QRTZ_FIRED_TRIGGERS;
TRUNCATE table QRTZ_PAUSED_TRIGGER_GRPS;
TRUNCATE table QRTZ_SCHEDULER_STATE;
TRUNCATE table QRTZ_LOCKS;
TRUNCATE table QRTZ_SIMPLE_TRIGGERS;
TRUNCATE table QRTZ_SIMPROP_TRIGGERS;
TRUNCATE table QRTZ_CRON_TRIGGERS;
TRUNCATE table QRTZ_BLOB_TRIGGERS;
TRUNCATE table QRTZ_TRIGGERS;
TRUNCATE table QRTZ_JOB_DETAILS;
TRUNCATE table QRTZ_CALENDARS;

