#yaml
server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: postgresql
  ###########################################################
  ###########################################################
  #spring安全认证配置
  security:
    user:
      name: admin
      password: admin

  # Specify the DBMS
  jpa:
    #    database: mysql
    # Show or not log for each sql query
    show-sql: true
    # Hibernate ddl auto (create, create-drop, update)
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: update
      # Naming strategy 定义HibernateO/R映射字段的命名策略
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    # stripped before adding them to the entity manager
    properties:
      hibernate:
        format_sql: true
        use_jdbc_metadata_defaults: false
  #        #        Hibernate的数据库方言。另外还有一些其他jpa配置信息，篇幅有限，可查阅jpa（hibernate）架构基本配置相关。
  #        dialect: org.hibernate.dialect.MySQL5Dialect

  #配置数据源
  datasource:
    # postgresql数据源
    postgresql:
      name: postgresql

      #      mysql的查询校验
      #      validation-query: SELECT 'x'
      #      oracle的查询校验
      #      validation-query: SELECT 'x'  FROM DUAL

      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000

      #druid相关配置
      #连接池中的minIdle数量以内的连接，空闲时间超过minEvictableIdleTimeMillis，则会执行keepAlive操作
      keep-alive: true
      #监控统计拦截的filters
      filters: stat
      # 建议配置为true，不影响性能，并且保证安全性。
      # 空闲检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 用户从连接池借用连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-borrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      #      type，目前没发现能起什么作用
      type: com.alibaba.druid.pool.DruidDataSource
#http编码配置
http:
  encoding:
    charset: UTF-8
    force: true
    enabled: true

#  是否启动swagger
swagger:
  show: true