server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: starter-origin
#http编码配置
http:
  encoding:
    charset: UTF-8
    force: true
    enabled: true

#  是否启动swagger
swagger:
  show: true