server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: jpa-hibernate-druid-multi-ds

  main:
    allow-bean-definition-overriding: true
  #配置数据源
  datasource:
    #    默认数据源，主数据源
    primary:
      name: primary
      #druid相关配置
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
#      driver-class-name: com.mysql.jdbc.Driver
      #基本属性，如果是使用druid，那么必须是url，如果是springboot2.0的默认数据源，那么是jdbc-url
      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
      username: root
      password: root
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      #      type，目前没发现能起什么作用
      type: com.alibaba.mybatisdruid.pool.DruidDataSource
    #      第二个数据源
    secondary:
      name: secondary
      #druid相关配置
      #监控统计拦截的filters
      filters: stat
#      driver-class-name: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
      #基本属性
      username: root
      password: root
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      #      type，目前没发现能起什么作用
      type: com.alibaba.mybatisdruid.pool.DruidDataSource
  # Specify the DBMS
  jpa:
#    database: mysql
    # Show or not log for each sql query
    show-sql: true
    # Hibernate ddl auto (create, create-drop, update)
    generate-ddl: true
    hibernate:
      ddl-auto: update
      # Naming strategy 定义HibernateO/R映射字段的命名策略
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    # stripped before adding them to the entity manager
#    properties:
#      hibernate:
#        #        Hibernate的数据库方言。另外还有一些其他jpa配置信息，篇幅有限，可查阅jpa（hibernate）架构基本配置相关。
#        dialect: org.hibernate.dialect.MySQL5Dialect

#http编码配置
http:
  encoding:
    charset: UTF-8
    force: true
    enabled: true